#!/usr/bin/env python

from db import init_db, Bean, Roast

path_to_db = './My Database.sqlite'

db = init_db(path_to_db)
for bean in sorted(Bean.select(), key=lambda b: b.name):
    print(bean.name)

print("\n\n-----\n\n")

for roast in Roast.select().order_by(Roast.timestamp.desc()):
    name = u", ".join(map(lambda b: b.name, roast.beans))

    print(u"{} : {}".format(roast.timestamp, name))
